### ISSUE TITLE
Should be SIDES?

### ISSUE THREAD

**Issue by bgranzow** [SNLComputation/lgrtk#13]
There is a duplicated condition in the link below.
I suspect the second `else if (type == ELEMS)` should be changed to `else if (type == SIDES)`.

https://github.com/SNLComputation/lgrtk/blob/770aa7a3292029a7b63da823deeb13a335efb5e5/v2/src/lgr_disc.cpp#L254

This currently results in a compilation error w/ gcc 7.3.0

**Comment by ibaned** [comment]
Thanks! fixed in d94d6ee
