### ISSUE TITLE
Include external yaml files in simulation input

### ISSUE THREAD

**Issue by tjfulle** [SNLComputation/lgrtk#22]
# What

A `!include: <yaml file>` directive to include external yaml file in lgrtk input file.

# Why

It would be incredibly useful to `!include: mesh.yaml` to include the mesh, or `!include: materials.yaml` to include materials, etc.  Albany has a directive to specify an external material file, but I think a general include directive would be generally more useful.

# Implementation ideas

The yaml standard does not provide a specification for this feature.  A possible implementation would be to look for the directive `!include` and interpret the associated value as a filename to load:

```cpp
if (key == “!include”)
{
  // Include external file, `value` is the filename
  if (!file_exists(value))
  {
    throw file_not_found_error(value);
  }
  auto contents = load_yaml_file(value);
  this->update(contents);
}
```

**Comment by micpowe** [comment]
Here's how Ansible (a RedHat configuration automation project) handles includes in yaml:

https://docs.ansible.com/ansible/latest/modules/include_module.html

The code is GPLv3 and python, but maybe there are some good ideas in the documentation.

**Comment by ibaned** [comment]
This is done!
With the most recent Omega_h, you can do exactly what Ansible does:
```yaml
big block:
   include: contents_of_big_block.yaml
```
